/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisorExternoRouteImport } from './routes/visor-externo'
import { Route as VisorRouteImport } from './routes/visor'
import { Route as MusicaRouteImport } from './routes/musica'
import { Route as ImagenesRouteImport } from './routes/imagenes'
import { Route as CombateRouteImport } from './routes/combate'
import { Route as IndexRouteImport } from './routes/index'

const VisorExternoRoute = VisorExternoRouteImport.update({
  id: '/visor-externo',
  path: '/visor-externo',
  getParentRoute: () => rootRouteImport,
} as any)
const VisorRoute = VisorRouteImport.update({
  id: '/visor',
  path: '/visor',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicaRoute = MusicaRouteImport.update({
  id: '/musica',
  path: '/musica',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagenesRoute = ImagenesRouteImport.update({
  id: '/imagenes',
  path: '/imagenes',
  getParentRoute: () => rootRouteImport,
} as any)
const CombateRoute = CombateRouteImport.update({
  id: '/combate',
  path: '/combate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combate': typeof CombateRoute
  '/imagenes': typeof ImagenesRoute
  '/musica': typeof MusicaRoute
  '/visor': typeof VisorRoute
  '/visor-externo': typeof VisorExternoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combate': typeof CombateRoute
  '/imagenes': typeof ImagenesRoute
  '/musica': typeof MusicaRoute
  '/visor': typeof VisorRoute
  '/visor-externo': typeof VisorExternoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combate': typeof CombateRoute
  '/imagenes': typeof ImagenesRoute
  '/musica': typeof MusicaRoute
  '/visor': typeof VisorRoute
  '/visor-externo': typeof VisorExternoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/combate'
    | '/imagenes'
    | '/musica'
    | '/visor'
    | '/visor-externo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/combate' | '/imagenes' | '/musica' | '/visor' | '/visor-externo'
  id:
    | '__root__'
    | '/'
    | '/combate'
    | '/imagenes'
    | '/musica'
    | '/visor'
    | '/visor-externo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombateRoute: typeof CombateRoute
  ImagenesRoute: typeof ImagenesRoute
  MusicaRoute: typeof MusicaRoute
  VisorRoute: typeof VisorRoute
  VisorExternoRoute: typeof VisorExternoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visor-externo': {
      id: '/visor-externo'
      path: '/visor-externo'
      fullPath: '/visor-externo'
      preLoaderRoute: typeof VisorExternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visor': {
      id: '/visor'
      path: '/visor'
      fullPath: '/visor'
      preLoaderRoute: typeof VisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musica': {
      id: '/musica'
      path: '/musica'
      fullPath: '/musica'
      preLoaderRoute: typeof MusicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagenes': {
      id: '/imagenes'
      path: '/imagenes'
      fullPath: '/imagenes'
      preLoaderRoute: typeof ImagenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combate': {
      id: '/combate'
      path: '/combate'
      fullPath: '/combate'
      preLoaderRoute: typeof CombateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombateRoute: CombateRoute,
  ImagenesRoute: ImagenesRoute,
  MusicaRoute: MusicaRoute,
  VisorRoute: VisorRoute,
  VisorExternoRoute: VisorExternoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
